import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/navigate/navbar';



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: { 
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className='flex flex-col h-screen'>
        <NavBar />
        <div className='flex-grow flex-wrap' >
        {children}
        
        </div>
        <div className='flex-none bg-gray-200 pt-4 px-12'>
          <footer >
            varsityscoop
          </footer>
        </div>
        
        
        </body>
    </html>
  )
}
