import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className='flex h-screen'>
        <div className='flex-none w-3/12 bg-gray-200 p-4 hidden md:block'>
        navbar
        </div>
        <div className='flex-1 p-4 overflow-y-auto max-h-screen' >
          
            {children}
        
        </div>
        <div className='flex-none w-3/12 bg-gray-200 p-4 hidden lg:block'>
          profile
        </div>
        
        
        </body>
    </html>
  )
}
